<?php

namespace ContainerDybC8XW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FtTl6VsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FtTl6Vs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FtTl6Vs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'auteurRepository' => ['privates', 'App\\Repository\\AuteurRepository', 'getAuteurRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'auteurRepository' => 'App\\Repository\\AuteurRepository',
            'paginator' => '?',
        ]);
    }
}
