<?php

namespace ContainerDybC8XW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AP0zWrPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aP0zWrP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aP0zWrP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'genreRepository' => ['privates', 'App\\Repository\\GenreRepository', 'getGenreRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'genreRepository' => 'App\\Repository\\GenreRepository',
            'paginator' => '?',
        ]);
    }
}
