<?php

namespace ContainerDybC8XW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLivreService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.PjlP4R0.App\Entity\Livre' shared service.
     *
     * @return \App\Entity\Livre
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.PjlP4R0": it references class "App\\Entity\\Livre" but no such service exists.');
    }
}
