<?php

namespace Container74PxP4f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XHoTv56Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xHoTv56' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xHoTv56'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'auteur' => ['privates', '.errored..service_locator.xHoTv56.App\\Entity\\Auteur', NULL, 'Cannot autowire service ".service_locator.xHoTv56": it references class "App\\Entity\\Auteur" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'auteur' => 'App\\Entity\\Auteur',
            'entityManager' => '?',
        ]);
    }
}
