<?php

namespace Container74PxP4f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuteurService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.PsDS_hI.App\Entity\Auteur' shared service.
     *
     * @return \App\Entity\Auteur
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.PsDS_hI": it references class "App\\Entity\\Auteur" but no such service exists.');
    }
}
