<?php

namespace ContainerAw5Ib64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLivre2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.a64LFR_.App\Entity\Livre' shared service.
     *
     * @return \App\Entity\Livre
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.a64LFR_": it references class "App\\Entity\\Livre" but no such service exists.');
    }
}
