<?php

namespace ContainerSG1x72j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q6BsKYQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q6BsKYQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q6BsKYQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'genre' => ['privates', '.errored..service_locator.q6BsKYQ.App\\Entity\\Genre', NULL, 'Cannot autowire service ".service_locator.q6BsKYQ": it references class "App\\Entity\\Genre" but no such service exists.'],
        ], [
            'genre' => 'App\\Entity\\Genre',
        ]);
    }
}
