<?php

namespace ContainerFfSihDA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenreService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.1S2iSUY.App\Entity\Genre' shared service.
     *
     * @return \App\Entity\Genre
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.1S2iSUY": it references class "App\\Entity\\Genre" but no such service exists.');
    }
}
