<?php

namespace ContainerCULhOIb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H7oceCJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.h7oceCJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.h7oceCJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AuteurController::delete' => ['privates', '.service_locator.xHoTv56', 'get_ServiceLocator_XHoTv56Service', true],
            'App\\Controller\\AuteurController::edit' => ['privates', '.service_locator.xHoTv56', 'get_ServiceLocator_XHoTv56Service', true],
            'App\\Controller\\AuteurController::index' => ['privates', '.service_locator.dZK.biq', 'get_ServiceLocator_DZK_BiqService', true],
            'App\\Controller\\AuteurController::new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\AuteurController::show' => ['privates', '.service_locator.PsDS_hI', 'get_ServiceLocator_PsDSHIService', true],
            'App\\Controller\\LivreController::delete' => ['privates', '.service_locator.PjlP4R0', 'get_ServiceLocator_PjlP4R0Service', true],
            'App\\Controller\\LivreController::edit' => ['privates', '.service_locator.PjlP4R0', 'get_ServiceLocator_PjlP4R0Service', true],
            'App\\Controller\\LivreController::index' => ['privates', '.service_locator.fgyhf2I', 'get_ServiceLocator_Fgyhf2IService', true],
            'App\\Controller\\LivreController::new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\LivreController::show' => ['privates', '.service_locator.a64LFR_', 'get_ServiceLocator_A64LFRService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AuteurController:delete' => ['privates', '.service_locator.xHoTv56', 'get_ServiceLocator_XHoTv56Service', true],
            'App\\Controller\\AuteurController:edit' => ['privates', '.service_locator.xHoTv56', 'get_ServiceLocator_XHoTv56Service', true],
            'App\\Controller\\AuteurController:index' => ['privates', '.service_locator.dZK.biq', 'get_ServiceLocator_DZK_BiqService', true],
            'App\\Controller\\AuteurController:new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\AuteurController:show' => ['privates', '.service_locator.PsDS_hI', 'get_ServiceLocator_PsDSHIService', true],
            'App\\Controller\\LivreController:delete' => ['privates', '.service_locator.PjlP4R0', 'get_ServiceLocator_PjlP4R0Service', true],
            'App\\Controller\\LivreController:edit' => ['privates', '.service_locator.PjlP4R0', 'get_ServiceLocator_PjlP4R0Service', true],
            'App\\Controller\\LivreController:index' => ['privates', '.service_locator.fgyhf2I', 'get_ServiceLocator_Fgyhf2IService', true],
            'App\\Controller\\LivreController:new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\LivreController:show' => ['privates', '.service_locator.a64LFR_', 'get_ServiceLocator_A64LFRService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AuteurController::delete' => '?',
            'App\\Controller\\AuteurController::edit' => '?',
            'App\\Controller\\AuteurController::index' => '?',
            'App\\Controller\\AuteurController::new' => '?',
            'App\\Controller\\AuteurController::show' => '?',
            'App\\Controller\\LivreController::delete' => '?',
            'App\\Controller\\LivreController::edit' => '?',
            'App\\Controller\\LivreController::index' => '?',
            'App\\Controller\\LivreController::new' => '?',
            'App\\Controller\\LivreController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AuteurController:delete' => '?',
            'App\\Controller\\AuteurController:edit' => '?',
            'App\\Controller\\AuteurController:index' => '?',
            'App\\Controller\\AuteurController:new' => '?',
            'App\\Controller\\AuteurController:show' => '?',
            'App\\Controller\\LivreController:delete' => '?',
            'App\\Controller\\LivreController:edit' => '?',
            'App\\Controller\\LivreController:index' => '?',
            'App\\Controller\\LivreController:new' => '?',
            'App\\Controller\\LivreController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
