<?php

namespace ContainerQConiwy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_RxHUamUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.RxHUamU' shared service.
     *
     * @return \Knp\Component\Pager\PaginatorInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\LivreController::index()": the $paginator argument is type-hinted with the non-existent class or interface: "Knp\\Component\\Pager\\PaginatorInterface".');
    }
}
