<?php

namespace ContainerQConiwy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KBdcr9cService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KBdcr9c' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KBdcr9c'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'livreRepository' => ['privates', 'App\\Repository\\LivreRepository', 'getLivreRepositoryService', true],
            'paginator' => ['privates', '.errored.RxHUamU', NULL, 'Cannot determine controller argument for "App\\Controller\\LivreController::index()": the $paginator argument is type-hinted with the non-existent class or interface: "Knp\\Component\\Pager\\PaginatorInterface".'],
        ], [
            'livreRepository' => 'App\\Repository\\LivreRepository',
            'paginator' => '?',
        ]);
    }
}
