<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUFqSu2G\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUFqSu2G/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUFqSu2G.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUFqSu2G\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUFqSu2G\App_KernelDevDebugContainer([
    'container.build_hash' => 'UFqSu2G',
    'container.build_id' => '769f912e',
    'container.build_time' => 1641133182,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUFqSu2G');
