<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAw5Ib64\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAw5Ib64/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAw5Ib64.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAw5Ib64\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAw5Ib64\App_KernelDevDebugContainer([
    'container.build_hash' => 'Aw5Ib64',
    'container.build_id' => '33ba9ec6',
    'container.build_time' => 1641148148,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAw5Ib64');
