<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXkM4FuN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXkM4FuN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXkM4FuN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXkM4FuN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXkM4FuN\App_KernelDevDebugContainer([
    'container.build_hash' => 'XkM4FuN',
    'container.build_id' => 'e4ac1751',
    'container.build_time' => 1641238182,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXkM4FuN');
