<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'auteur_index' => [[], ['_controller' => 'App\\Controller\\AuteurController::index'], [], [['text', '/auteur/']], [], [], []],
    'auteur_new' => [[], ['_controller' => 'App\\Controller\\AuteurController::new'], [], [['text', '/auteur/new']], [], [], []],
    'auteur_show' => [['id'], ['_controller' => 'App\\Controller\\AuteurController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/auteur']], [], [], []],
    'auteur_edit' => [['id'], ['_controller' => 'App\\Controller\\AuteurController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/auteur']], [], [], []],
    'auteur_delete' => [['id'], ['_controller' => 'App\\Controller\\AuteurController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/auteur']], [], [], []],
    'genre_index' => [[], ['_controller' => 'App\\Controller\\GenreController::index'], [], [['text', '/genre/']], [], [], []],
    'genre_new' => [[], ['_controller' => 'App\\Controller\\GenreController::new'], [], [['text', '/genre/new']], [], [], []],
    'genre_show' => [['id'], ['_controller' => 'App\\Controller\\GenreController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/genre']], [], [], []],
    'genre_edit' => [['id'], ['_controller' => 'App\\Controller\\GenreController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/genre']], [], [], []],
    'genre_delete' => [['id'], ['_controller' => 'App\\Controller\\GenreController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/genre']], [], [], []],
    'livre_index' => [[], ['_controller' => 'App\\Controller\\LivreController::index'], [], [['text', '/livre/']], [], [], []],
    'livre_new' => [[], ['_controller' => 'App\\Controller\\LivreController::new'], [], [['text', '/livre/new']], [], [], []],
    'livre_show' => [['id'], ['_controller' => 'App\\Controller\\LivreController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/livre']], [], [], []],
    'livre_edit' => [['id'], ['_controller' => 'App\\Controller\\LivreController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/livre']], [], [], []],
    'livre_delete' => [['id'], ['_controller' => 'App\\Controller\\LivreController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/livre']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
];
