<?php

namespace ContainerUFqSu2G;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_R1pjxySService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.r1pjxyS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.r1pjxyS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'livreRepository' => ['privates', 'App\\Repository\\LivreRepository', 'getLivreRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'livreRepository' => 'App\\Repository\\LivreRepository',
            'paginator' => '?',
        ]);
    }
}
