<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Auteur extends \App\Entity\Auteur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Auteur' . "\0" . 'id', 'nom_prenom', '' . "\0" . 'App\\Entity\\Auteur' . "\0" . 'sexe', '' . "\0" . 'App\\Entity\\Auteur' . "\0" . 'date_de_naissance', '' . "\0" . 'App\\Entity\\Auteur' . "\0" . 'nationalite', '' . "\0" . 'App\\Entity\\Auteur' . "\0" . 'Livres'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Auteur' . "\0" . 'id', 'nom_prenom', '' . "\0" . 'App\\Entity\\Auteur' . "\0" . 'sexe', '' . "\0" . 'App\\Entity\\Auteur' . "\0" . 'date_de_naissance', '' . "\0" . 'App\\Entity\\Auteur' . "\0" . 'nationalite', '' . "\0" . 'App\\Entity\\Auteur' . "\0" . 'Livres'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Auteur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomPrenom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomPrenom', []);

        return parent::getNomPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomPrenom(string $nom_prenom): \App\Entity\Auteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomPrenom', [$nom_prenom]);

        return parent::setNomPrenom($nom_prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexe(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexe', []);

        return parent::getSexe();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexe(string $sexe): \App\Entity\Auteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexe', [$sexe]);

        return parent::setSexe($sexe);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDeNaissance(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDeNaissance', []);

        return parent::getDateDeNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDeNaissance(\DateTimeInterface $date_de_naissance): \App\Entity\Auteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDeNaissance', [$date_de_naissance]);

        return parent::setDateDeNaissance($date_de_naissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getNationalite(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNationalite', []);

        return parent::getNationalite();
    }

    /**
     * {@inheritDoc}
     */
    public function setNationalite(string $nationalite): \App\Entity\Auteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNationalite', [$nationalite]);

        return parent::setNationalite($nationalite);
    }

    /**
     * {@inheritDoc}
     */
    public function getLivres(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLivres', []);

        return parent::getLivres();
    }

    /**
     * {@inheritDoc}
     */
    public function addLivre(\App\Entity\Livre $livre): \App\Entity\Auteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLivre', [$livre]);

        return parent::addLivre($livre);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLivre(\App\Entity\Livre $livre): \App\Entity\Auteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLivre', [$livre]);

        return parent::removeLivre($livre);
    }

}
