<?php

namespace ContainerVCcfmUM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuteur2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.xHoTv56.App\Entity\Auteur' shared service.
     *
     * @return \App\Entity\Auteur
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.xHoTv56": it references class "App\\Entity\\Auteur" but no such service exists.');
    }
}
