<?php

namespace ContainerVCcfmUM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuteurRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\AuteurRepository' shared autowired service.
     *
     * @return \App\Repository\AuteurRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\AuteurRepository'] = new \App\Repository\AuteurRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
