<?php

namespace ContainerVCcfmUM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLivreRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\LivreRepository' shared autowired service.
     *
     * @return \App\Repository\LivreRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\LivreRepository'] = new \App\Repository\LivreRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
